name: macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          - 'head'
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.64.1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run test
      run: |
        rake test
    - name: Run packaging
      run: |
        rake package
        gem install --local pkg/gem-compiler-*.gem
