name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '2.6'
          - '2.5'
          - '2.4'
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.38.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install Bundler
      run: |
        gem install bundler --conservative --no-document
    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run test
      run: |
        rake test
    - name: Run packaging
      run: |
        rake package
        gem install --local pkg/gem-compiler-*.gem
